on:
  push:
    branches: [ main ]
jobs:
  release-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        
      - name: Compile document
        run: typst compile Loanwords-Quiz.typ --font-path ./fonts

      - name: Recreate release
        run: |
          gh release delete latest --cleanup-tag --yes --repo $GITHUB_REPOSITORY || true
          gh release create latest --latest --title "Japanese Loanwords Quiz" --repo $GITHUB_REPOSITORY "Loanwords-Quiz.pdf"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
