name: Create Release
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: update apt and install fonts-noto-cjk
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
          
      - name: Compile typst document
        uses: typst-community/setup-typst@v4
      - run: typst compile Loanwords-Quiz.typ

      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ github.ref_name }}"
          files: Loanwords-Quiz.pdf